### ISSUE TITLE
Steal@1.x not loading devDeps is problematic for the canjs repo tests

### ISSUE THREAD

**Issue by marshallswain** [stealjs/steal#1079]
I tried updating the canjs/canjs repo to the latest Steal today, but ran into a snag caused by [Steal ignoring devDependencies of other dependencies](https://github.com/stealjs/steal/blob/3c673de80091c8a158bb904e15f6851b042f84a1/ext/npm-crawl.js#L253-L256).

The scenario is that canjs requires can-compute's tests.  can-compute's tests require can-define, which is listed in devDependencies.  Since it's in can-compute's devDependencies, Steal ends up trying to load it from `http://localhost:8080/can-define/map/map.js` instead of in canjs's  node_modules folder (where it is already installed because it is a dependency of canjs.

My thoughts on solving this (each is an independent solution):
 1. We add any of the devDependencies used in tests into each modules dependencies.  Not ideal.
 2. We write a script for canjs that copies the `can-*` modules from the node_modules folder into the canjs/canjs project in order for tests to run.
 3. We make Steal crawl devDependencies.

Maybe there are more options, but that's all I've got for now.

**Comment by justinbmeyer** [comment]
Why can't it work like `0.16` and "walk up" to dependencies it can't find?  There should be a valid `can-define` version pointed at by `canjs`'s `dependencies`.

**Comment by matthewp** [comment]
This is not related to any changes in Steal 1.0. This has always worked this way, afaik. The reason is that devDependencies are not installed in child packages. It *happens* to exist anyways, in this case. But wouldn't it most cases. 

The code in question is here: https://github.com/stealjs/steal/blob/3c673de80091c8a158bb904e15f6851b042f84a1/ext/npm-crawl.js#L253-L256

**Comment by matthewp** [comment]
I think the original reason why we ignored devDepedencies was probably because we used to load all npm packages, and ignore devDependencies preventing a lot of 404s (as devDeps are not installed for child dependencies).

Since we now load deps lazily I don't think this problem exists. When we come across `require('foo')` we should try and load that dependency even if it is a devDep.

**Comment by marshallswain** [comment]
I don't understand why upgrading from 0.16 to 1.x breaks this.  Here are the only changes I made: https://github.com/canjs/canjs/pull/3028/files.  Am I missing something?

**Comment by matthewp** [comment]
I don't know why that would make a difference either.

**Comment by matthewp** [comment]
Fixed in 1.2.9 https://github.com/stealjs/steal/releases/tag/v1.2.9
