### ISSUE TITLE
Warning for unresolved packages not installed as dep or devDep

### ISSUE THREAD

**Issue by andrejewski** [stealjs/steal#1205]
If someone installs an NPM package without saving it to the package.json, as a fall-through warning message we can say "It looks like "{packageName}" exists in node_modules but is not in your package.json's dependencies or devDependencies, please add it if this is your intention." Something to that effect.

**Comment by matthewp** [comment]
Hey @andrejewski, I don't think we could give that good of an error message because we don't actually know if a module is part of a package unless it is in the package.json somewhere. So we wouldn't know that the package exists in node_modules. This is the downside to browser-side tooling.

We should have much better error messaging though, for sure. Once the slim-loader lands I'll feel much better about adding additional dev-time tooling features to steal. For example we could collect more information about loading and create a message like:

```json
Could not load {moduleName}
  - Is NPM module: false
  - Is a plugin: false
```

And maybe even put this in the DOM (optionally, most likely).

**Comment by m-mujica** [comment]
@matthewp how would you implement this? 

Since the error comes from the `fetch` hook itself, I was thinking that we could an extension a la `extension-depCache` where `loader.fetch` is overriden to catch `Not found` errors and that way we could rethrow a nice error.

This extension would be added after all the other so we are certain that all the `fetch` pipeline was exhausted. 

yay? nay?

**Comment by m-mujica** [comment]
Now I'm thinking this should be somewhere in the npm extension

**Comment by matthewp** [comment]
I think in npm so we want to catch possible npm misuse. But otherwise, that sounds like a good way to do it. The npm-extension already some some stuff that detects 404s, I believe, so maybe look there to see how to do that properly.

**Comment by m-mujica** [comment]
The problem with the npm extension is that it doesn't know the identifier referers to a npm package, `normalize` won't find the package anywhere and then `fetch` will just call its parent method https://github.com/stealjs/steal/blob/12c3dffdf3559d92516485e442817e275a02c877/ext/npm-extension.js#L313

I guess the extension is the way to go.

**Comment by matthewp** [comment]
Yeah, I would add an else there that checks if the moduleName is a bare specifier (meaning doesn't start with `.` or `@` mainly) and catch the error when it is a bare specifier. You're right that we don't *know* that it refers to an npm package. That's why the warning needs to be somewhat vague like "This is maybe an npm package?".  Most of the time bare specifiers *will* be npm packages though.
