### ISSUE TITLE
broken myhub example (looks like a problem with steal-less?)

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#1261]
With a basic app that loads less, the production build seems to fail.

I've made a version of myhub here: https://github.com/justinbmeyer/myhub

I'm using node __5__.  Though everyone else seemed to have this problem.

To see it you can open `index.html` (I've committed the build).  In the dev-tools you'll see:

<img width="1365" alt="cursor_and_localhost_8080_index_html" src="https://user-images.githubusercontent.com/78602/29903629-b6e0ddb4-8db9-11e7-9d48-23bcb4bb09bd.png">

`myhub.js` just has:

```js
import "./myhub.less";
```

To run the build `npm run build`.

**Comment by PieterSwitten** [comment]
@justinbmeyer Same problem here, going back to steal 1.5.9 fixes the issue

**Comment by matthewp** [comment]
https://github.com/stealjs/steal/pull/1262 should fix it. Will confirm once it's released.

Note that this wouldn't occur if the guide used `stealTools.optimize` rather than stealTools.build, since the former doesn't do run-time dependency detection. I might update the guide to use that instead of build, since I'm working on guide stuff now anyways.

**Comment by matthewp** [comment]
Release happening now...

**Comment by matthewp** [comment]
Working here now in 1.5.11

![screen shot 2017-08-31 at 9 20 45 am](https://user-images.githubusercontent.com/361671/29925251-b2404e42-8e2d-11e7-9184-4d0c859dd06b.png)

**Comment by matthewp** [comment]
Release notes: https://github.com/stealjs/steal/releases/tag/v1.5.11
