### ISSUE TITLE
More complex app example

### ISSUE THREAD

**Issue by imiric** [stealjs/steal#387]
Hi,

I'm trying to integrate StealJS into a typical Express app, but am finding it difficult to understand what exact static files I should expose in the server.

For example, I would like to have the following directory structure:

```
myapp
├── client
│  ├── app.js
│  ├── templates
│  │  └── index.html
│  └── vendor
│     └── js
│        └── steal
│           ├── steal.js
│           ├── stealconfig.js
│           └── <other steal files>
├── package.json
└── server
   └── app.js
```

I can serve all static files under `client/vendor`, but since Steal doesn't have access to my `package.json`, it doesn't find any app entries or dependencies. The quick start guide mentions `http-server` which exposes the entire working directory (including `node_modules`) and while this is fine for testing purposes, I wouldn't really want to have this in production.

Is there an idiomatic way of accomplishing this with Steal+Express, while keeping the above directory structure?

Thanks!

**Comment by marshallswain** [comment]
If you create a separate package.json file in your `client` folder it will allow you to keep your client node_modules cleanly separated from your server node_modules.  You're right that in development it's nice to have the node_modules folder there, but not on the production server.  To accomplish this, you can use do something along these lines once you're ready to publish:

  1. Use [steal-tools build](http://stealjs.com/docs/steal-tools.cmd.build.html) to package your code into a nice little .js bundle.  If you have used css dependencies, this will also create a .css bundle.
  2. Change your index.html file to use the production bundle instead of the development files.  Don't forget to link your freshly-package .css file.
  3. Setup your publishing tool to exclude your `client/node_modules` folder.  If you're using FTP, tell your FTP client to exclude it.  Some hosting providers' tools use an .npmignore file.  Or if you're publishing using GIT, you can use a .gitignore file.

If you follow the [quick start guide](http://stealjs.com/docs/StealJS.quick-start.html), the only step left to publish would be to keep node_modules from being published to your production server.

**Comment by matthewp** [comment]
I concur with @marshallswain here.  StealTool's build will by default write to `dist/bundles`. So I typically put other static stuff in `dist/images`, `dist/fonts`, etc. and then serve the `dist` folder as my static folder in production.  Of course you're free to call this `public` or whatever else you want.

Please do let me know how you eventually structure things, this would make a good article I think.

**Comment by imiric** [comment]
I agree with you, that's the proper strategy for production. But is there a way of making it work in _development_ as well, without having to change my `index.html`? I'd rather serve un{concatenat,minifi,uglifi}ed files during development to aid in debugging / rapid prototyping, and have the build step there for actual deployments.

What I was looking for is basically the quick start guide, but for a more complex structure (with a "real" web server like Express), to see what's the best way of hooking this up. (The guide already alludes to it with "If you already have a webserver running locally, you can skip this step", but doesn't give any additional information about it.) Or even the repo of an already built, fully-featured project that uses StealJS on Github. Is there such a thing? That would indeed be helpful.

Thanks for your help.

**Comment by matthewp** [comment]
Closing in favor of https://github.com/stealjs/steal/issues/866, which is a more complex app example.
