### ISSUE TITLE
`global` is not defined inside the module in production

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#436]
The problem with this module (and particular source) in production:

https://github.com/treojs/treo/blob/master/lib/index.js#L172

in dev mode referece to `global.indexedDB` and global there is window object so everthing works, but after build it can not access global inside the module. 

Something wrong with module format?

**Comment by matthewp** [comment]
where is global defined?

**Comment by whitecolor** [comment]
What do you mean? I gave a like to lib code, in dev it works ok, in production no.

**Comment by matthewp** [comment]
Yes, it's commonjs and for commonjs we set a "global".  In production it is transpiled to AMD so no "global".  It's a problem, I'm not sure what the proper solution is off the top of my head though.

**Comment by whitecolor** [comment]
currenlty as workaround inside this module I do a trick to make it work:

```javascript
window.global = window
```

So are you going to solove this?

**Comment by matthewp** [comment]
Yes, when I can think of a good solution. It's a bug.  I'm sure we can permanently set a window.global like that because some other libraries might check for `global` to detect that they are running in Node.  I wonder what browserify/webpack do to this type of code.  We could possibly check for `global` during the build and shim it in for modules that need it...

**Comment by whitecolor** [comment]
won't it be just enoth to pass `global` param to AMD closure equal to `window`?

**Comment by matthewp** [comment]
Maybe, my only concern there is that if code is detecting `global` to know if they are in Node.js or not.  But I wouldn't be opposed to that change for AMD.

**Comment by matthewp** [comment]
This is fixed.
