### ISSUE TITLE
package.json's `system` of dependencies

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#572]
How does steal handles `system` in `package.json` of dependecy modules? Does it merge them or what it it suppose to do?

I have a dep module that have package.json and `system` inside, and ther `baseURL` defined. While loading it takes this `baseURL` and applied it. So may app was loaded with `baseURL` from dependency module. 

So it seem that it merges `system`s of depencency modules with `system` of dependant (app) module. Is it by design?

**Comment by justinbmeyer** [comment]
System.baseUrl should probably not be set in a package. Instead, directories.lib should be used.

**Comment by matthewp** [comment]
Yes, adding config to package.json `system` is the same as using `System.config({ ... });` anywhere in your code, it is global. It's possible (theoretically, though probably not practical) to scope some types of config, like map, but the majority of it, like baseURL is always global. I wouldn't set baseURL in your config, but rather do so in the script tag.

**Comment by whitecolor** [comment]
1)  I tried to use script attribute but it didn't work for me
```HTML
<script src="/node_modules/steal/steal.js" base-url="app" 
```
I tried `data-base-url` either, should it work?

2) Instead I had for now to scope using `envs` in package.json and set env on script tag (it generously works). What is about using envs for such cases? (for example **internal** development need of the package)? 

3) And one me thing about `envs` it seem that it appy `map/baseURL`, but dont `npmIgnore`, `npmAlgorigthm`? Is it by design?

**Comment by matthewp** [comment]
Not sure what your issue is, base-url in the script tag should definitely change your baseURL. If you have an example of this failing please file a bug on it.

Yes, envs can be used for this. It's meant to be something that you can change to suit your needs. However there might be some code in the wild (like plugins) that checking the env and expect it to be development/production. This is something that's always felt weird to be able env and that I don't like about it.  But if you are not running into issues you must not be using those plugins.

Using envs should definitely apply **map**.  npmIgnore and npmAlgorithm however will not, those are not global config, it's config specifically for the NPM plugin and that config is accumulated while crawling.

**Comment by matthewp** [comment]
Going to close as I don't think there's a bug here. I don't mind you filing lots of issues when you have found a bug, that's great actually and you help stuff get fixed so keep doing that, but general questions like this are better asked in the forums: http://forums.donejs.com/

**Comment by whitecolor** [comment]
@matthewp 
Could you please check:

- git clone https://github.com/whitecolor/can-hot
- npm install
- npm start
- open http://localhost:7000 
- check System.env - it will be "can-hot-dev"
- check System.baseURL - it will be "http://localhost:7000/app/" (as in package.json it set for this env)
**base-url issue*** Then I do the following:
- in `index.html` remove `env="can-hot-dev"` and set `base-url="app"`
- go to http://localhost:7000 - app is not loaded with errors
- check System.baseURL - "http://localhost:7000/"

**npm envs map/npmIgnore/etc issue** Then I do the following:
- set again `env="can-hot-dev"`in `index.html`
- in `package.json` move global system config settings (`npmIgnore`, `npmAlgorithm`, `transpiler`, etc) to `can-hot-dev` env
- app does not load with errors

**Comment by matthewp** [comment]
Yeah, you don't want to set the baseUrl. Setting the baseUrl adjusts where all modules are located. This would mean that it would lookup jquery in `app/` which you don't want.

you want to specify a root folder for your project, that is what directories.lib is for:

```js
"system": {
  "directories": {
    "lib": "app"
  }
}
```

Cool project btw

**Comment by whitecolor** [comment]
@matthewp thanks, then couple of questions:
1) ok, I should not change base-URL, but why it is not changed using script attribute?
2) what is about other settings `npmIgnore, npmAlgorithm, transpiler` that do not apply to scpecific env actually, hav you tried it?

**Comment by matthewp** [comment]
Because you are also setting the `config` property which also sets the baseURL. If you are loading from node_modules you never need to set `config="package.json!npm"`, that's the default.  

Like I said, npmIgnore, npmAlgorithm, and transpiler are not env specific.  npmIgnore is not going to be needed anymore when https://github.com/stealjs/steal/pull/569 lands, the other two are possibilities, could discuss it.

**Comment by whitecolor** [comment]
@matthewp 
Some strange issues:
1) If in current version of `can-hot` leave just in `index.html`:
```
<script src="/node_modules/steal/steal.js" main="@empty">
```
and add
```
"directories": {
      "lib": "app"
    },
```
Then in index.html I change ('can-hot' to '../can-hot'):
```javascript
import canHot from '../can-hot' // because it should look it up relative to `app`.
```
But it doesn't load, and instead it gives an error:
```error
otentially unhandled rejection [2] TypeError: Error loading "undefined" at <unknown>
Cannot read property 'split' of undefined
    at Object.utils.moduleName.parse (http://localhost:7000/node_modules/steal/ext/npm-utils.js:96:32)
```
I placed an out put there in `npm-utils` and it seems that it tries to load tries to load module with name of packge.json `name` field.

Could you check it?

**Comment by matthewp** [comment]
"app" is a demo, right? In that case, why are you setting directories.lib? Directories.lib sets the root of your project. The root of your project is the base directory (because that is where can-hot.js is. If you put can-hot in a "src" folder then you would want to set directories.lib to the "src" folder.

It sounds like you are wanting to do conflicting things. You want the root of your "app" demo to be "app" but you still want to load can-hot.js from the base directory and load npm deps from "node_modules".  Why don't you just import your "app" demo using `main="app/app"` and then load everything else relative? That's how I always do demos.

**Comment by whitecolor** [comment]
Well no problems with loading in app with `app/` prefix to all modules, I just wanted to text how flexible config can be, but run in to different issues.

Especially I didn't like this issue with error I described (with trying to load package.json `name`) and it says nothing just an error - I added an debug output in `npm-utils` understand what it is tring to load. I understand that something wrong with config in this case, but it is still annoying to have an error without any clue what you are doing wrong. So I would check it in you place.)

**Comment by matthewp** [comment]
I can't spend all day every day hunting down your bugs. If you have more specific info about this "name" issue I'd definitely like to add warnings/errors that are more clear.

**Comment by whitecolor** [comment]
@matthewp I believe it is not my bugs, it's steal's bugs) 
```HTML
 <script src="/node_modules/steal/steal.js" main="@empty">
    import HMR from 'steal-hmr'
    import canHot from 'can-hot'
```
replace `can-hot` with `./can-hot` (is there any difference in this case?)
```HTML
 <script src="/node_modules/steal/steal.js" main="@empty">
    import HMR from 'steal-hmr'
    import canHot from './can-hot'
```

And you will get the error
```
Potentially unhandled rejection [2] TypeError: Error loading "undefined" at <unknown>
Cannot read property 'split' of undefined
    at Object.utils.moduleName.parse (http://localhost:7000/node_modules/steal/ext/npm-utils.js:96:32)
```

**Comment by matthewp** [comment]
You can't load modules relative that don't have a parent module (like from the page). I'll add a better error message about this.

**Comment by matthewp** [comment]
https://github.com/stealjs/system-npm/issues/99

**Comment by whitecolor** [comment]
Why it is trying to do something with `package name`?
