### ISSUE TITLE
NPM importing a dir doesn't attempt to import 'dir/index.js'

### ISSUE THREAD

**Issue by nlundquist** [stealjs/steal#581]
Using the 0.14.0-pre.8 release, trying to import the 'faker' mock data generator fails. When importing a directory, steal attempts to load 'directory.js' rather than 'directory/index.js'.

Running the isolated example linked below fails to import faker.
https://github.com/nlundquist/steal-faker

**Comment by matthewp** [comment]
Hey, so the 404s are expected. We don't actually know if a module is at `directory.js` or `directory/index.js` so the only thing we can do is try `directory.js` (which is the norm) and then fallback to `directory/index.js` if the first fails.

I tried this repo and that part is working. What's failing is that a module is not being correctly detected as CommonJS because it is doing `module["exports"] = ` and our CommonJS detection is missing it. Updating our regex to this: https://github.com/systemjs/systemjs/commit/8c5e170d7daa7448e5fe236fd0ee17eb8ed91cf4  would fix that.  When I apply that locally I can load your module.

This is a great example of a library using that pattern, I've never seen another module that uses it as much as this one. It sucks that there are so many 404s, it's not normal to find modules like this in the wild. But what we should do is, when we encounter this, is give a good console.log message that explains that the 404s are ok and nothing to worry about; they won't happen in production.

Additionally I'm interested in finding a way to cache in localstorage (or indexeddb or somewhere else) when this happens so on page refreshes we can avoid the 404s.

**Comment by nlundquist** [comment]
Thanks for the fix & details on the issue!

**Comment by nlundquist** [comment]
I've confirmed this issue is resolved.
