### ISSUE TITLE
Importing global from file differs in Safari & Chrome

### ISSUE THREAD

**Issue by nlundquist** [stealjs/steal#601]
Importing a JS file that contains an unmodularized global function results in different imports in Safari & Chrome.

In Chrome (and Firefox), the global, a function in this case, is imported. This behaviour seems to make sense.

In Safari, the import is an object with the expected import as an entry with the key being the name of the global, the other entries are functions not found in my code. 

I've demonstrated the issue in this test case:
https://github.com/nlundquist/steal-global-resize

**Comment by matthewp** [comment]
Hey, sorry for taking so long to get to this. First, awesome test project! Made it very easy for me to investigate the issue.

Turns out the problem is caused by a bug in Safari 9. The way the automatic global detection code works is before executing the global Steal keeps a map of all of the current globals and then after executing compares `window` to that map, and anything new is assumed to be the module's export.

The bug is that in Safari 9 `window.blur != window.blur`, and so it thinks `blur` was added by the library! This is true of a few other properties, not just blur.  Luckily Safari 10 fixes this issue and the test page works.

In general, I would avoid automatic global detection as the method is imperfect and susceptible to browser bugs like this one. Instead I would always use the meta config `exports` object to explicitly declare what the global's export is. Not only is it more correct, but you also avoid the expensive operation of looping over the global 2 times for each module.

Here's some docs about how to configure globals: http://stealjs.com/docs/StealJS.configuration.html#section_Configuringglobals
