### ISSUE TITLE
Using locate:// with CSS is broken.

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#648]
Related to #610, CSS is not working with `locate://` properly.  cc @nlundquist 

The first reason is that in development, the CSS will be inserted as a `<style>` tag so all paths will be relative to the current page.  This means that instead of `relative(parent, address);`, we probably need relative to the current URL.

@matthewp a few questions on how to proceed:

1.  Does steal include `@import`s with `css`?  I know it does for `less`.  But I don't think we bundle `css` imports.  If we do, we need to remove `@import` (but I don't think we are).  If we do not, we'll want to write out a path in the build that will be relative to the `css` file because it will be added as a `link` element.
2.  If absolute paths are written out, does steal's build handle this?  I'm sorta under the impression that steal will go and clean up any absolute paths to be relative when building out CSS.

**Comment by justinbmeyer** [comment]
@matthewp something like this breaks:

```
@import 'locate://bootstrap/dist/css/bootstrap.css';
@import 'locate://font-awesome/css/font-awesome.css';
```

It uses the wrong paths to `bootstrap` and `font-awesome`

**Comment by matthewp** [comment]
We don't include the `@import`ed css into the css bundle, but if you use `bundleAssets: true` that css file should be copied into dist/ and the urls updated to be relative to that location.

**Comment by matthewp** [comment]
However, since we have 2 css plugins currently this is a bit confusing, are you certain that it is the default css plugin that is not working with `locate://` and not done-css (which is what you are using if it's a donejs project).

Like I said in another issue, we should merge done-css with steal-css (getting rid of done-css). The original reason why I forked done-css was to avoid adding donejs-specific bulk to the css plugin but it's too much of a maintenance burden to have 2 plugins that do essentially the same thing.

**Comment by justinbmeyer** [comment]
I'm sure.  The underlying `relative` call is wrong.

**Comment by matthewp** [comment]
Was this fixed?

**Comment by matthewp** [comment]
Going to assume it's fixed, reopen if not.
