### ISSUE TITLE
Not able to load stache file outside of bundle

### ISSUE THREAD

**Issue by shaunstepanowich** [stealjs/steal#657]
#You are able to import js files that are not in a bundle, but if you attempt to load a stache file it will fail.

This is because can/view/stache/system is the can production dist is empty

Although you should not be doing this it seems like at the very least it should be documented, if not supported.

See forum post for full details:
http://forums.donejs.com/t/not-able-to-progressively-load-stache-file/214/6

**Comment by justinbmeyer** [comment]
To add a bit of clarity:

> This is because can/view/stache/system is not in the can production dist

`can/view/stache/system` is in the production bundle (I believe).  However, it's empty because it's not needed when you build a template to its export.

@shaunstepanowich You should build any other bundles you are going to load in production.  If you specify your templates in `bundle` similar to:

https://github.com/donejs/bitballs/blob/master/public/package.json#L64

Those will be built too and should have no problem loading in production.

I'm not sure where to document this as it crosses the stealjs / canjs divide.  I suppose steal, because for any plugins that are built to some other form (less, stache, etc), we don't also include the plugin code.  This is to keep the bundles more lightweight.

It might be possible (but possibly dangerous) to make it so those files are treated as `js` and alter their module names. This would allow the stache and less engines to be loaded if needed.

But yet again ... you should really never be doing that in a production build.

**Comment by shaunstepanowich** [comment]
Updated description for clarity to say can/view/stache/system is empty vs missing.

**Comment by matthewp** [comment]
Moving this to https://github.com/canjs/steal-stache/issues/5
