### ISSUE TITLE
Different Bundle Setup Than in Guide- Progressive Load

### ISSUE THREAD

**Issue by starlap** [stealjs/steal#709]
**Different Bundle Setup Than is Described in Guide**

**Explanation:**
When I run the build, I get a different file structure than is listed in the guide:
1.) Go to [Build Your Site](http://stealjs.com/docs/steal-tools.guides.progressive_loading.html#section_Buildyoursite)
2.) Look at the directory for the bundle structure
3.) My bundle structure is to look like this:

![bundle_structure](https://cloud.githubusercontent.com/assets/18269875/15376606/da13f260-1d0a-11e6-87d5-d145c81657e6.png)

4.) My actual bundle structure looks like this:

![screenshot4_bundlestructure](https://cloud.githubusercontent.com/assets/18269875/15376639/14d25054-1d0b-11e6-8388-07e38d8a04cf.png)

It is creating a structure with a new folder that has the same name as the root folder.  In order to finish testing, I copied app.js to the site folder. However, I noticed that app.js was being requested twice, in the html browser.  See below:

![html_2appjs](https://cloud.githubusercontent.com/assets/18269875/15378779/44a049b6-1d1b-11e6-85cf-ae5fb6d868d6.png)

**Comment by matthewp** [comment]
Arg, sorry about this. I guess we'll go with `site` since that's what it originally was. Will update it.

**Comment by roemhildtg** [comment]
Hello, I too am struggling with this a bit and have noticed another difference between the docs and [the sample app](https://github.com/stealjs/progressive-loading) with the use of `directories.lib` in package.json. 

The guide doesn't mention this, but it is used in the sample app repo. At first I was pretty confused as to why the bundler output app/filename instead of site/filename but after some digging I found [it in the docs](https://github.com/stealjs/steal/blob/0c3ddb285dfe968d6630bf0972f933c7016e98e2/docs/pages/configuration.md#specify-your-projects-root-folder) 

IMO, this should be linked or at least mentioned in the guide. 

This is where I'm confused, I hope its okay if I ask a question here.. if I have a project named `app` and I have a directory like this:

```
app/
       node_modules/
       src/
              app/  <----app files
              config/ <--config files
package.json
...
```

In my npm config for steal, I specify this:
```json
"main": "app/app/crud",
  "system": {
    "npmAlgorithm": "flat",
    "directories": {
      "lib": "src"
    },
    "bundleAssets": true,
    "bundle": [
      "app/config/utilities/views/Workorder",
      "app/config/utilities/workorders"
    ],
```

What is incorrect about this? Steal says `Error loading "index" at file app/index.js. and fails.

**Comment by matthewp** [comment]
That errors just loading your app?  I don't see anything wrong with it, except your bundle names should be be like `app/app/config/utilities/views/Workorder`

**Comment by roemhildtg** [comment]
@matthewp no errors when loading it in a browser, that's the buld error. At the end it says `ERROR: Build Failed` This may be getting off topic...is it okay if I pm you on gitter?

**Comment by matthewp** [comment]
I'm not going to be on gitter today. Can you paste your error message?

**Comment by roemhildtg** [comment]
The full output looks like this:
```
> steal-tools
X:\static_apps\crud>npm run build > output.txt
(node:6152) fs: re-evaluating native module sources is not supported. If you are
using the graceful-fs module, please update it to a more recent version.
(node:8548) fs: re-evaluating native module sources is not supported. If you are
using the graceful-fs module, please update it to a more recent version.
ERROR: Error loading "index" at file:X:/static_apps/crud/index.js
ENOENT: no such file or directory, open 'X:\static_apps\crud\index.js'
ERROR:
Build failed
```
I made some modifications to the file structure also...I got rid of the `src` and moved the app,config folder in the root. https://github.com/roemhildtg/can-crud-app/blob/master/package.json is how the project is setup.

I've been trying a few things like what you suggested, with the path of main & bundles too but it doesn't change the error.

**Comment by matthewp** [comment]
Sorry, I can't from that.  This is what I would do, start by getting rid of your `bundle` config? Still get the error? If not, the problem is with the bundles. Next I would (with bundles still removed) try removing all of the imports in your main and seeing if it works there; with absolutely nothing but a main it *should* work. Then start adding back the imports one-by-one until you find out which is a problem.

**Comment by roemhildtg** [comment]
No, that definitely helped, thank you! 

I commented out everything in main and eliminated the bundles config, and it still was having that error, so I looked into my node packages. The problem was, I had several packages that had `"main": "index" and after changing them to `"main": "package-name/index"` the build completes. A silly mistake, I didn't realize this would cause problems since I was never importing the index file from the packages, just a couple of the modlets from each. 

While the build says "Build completed successfully", however, steal-tools seems to be ignoring my paths in the "bundles" array, meaning they are not getting built into the main bundle or their side bundles.
