### ISSUE TITLE
Default main when using npm should include the package name.

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#721]
I had to change:

```
<script src="./node_modules/steal/steal.js"></script>
```

to

```
<script src="./node_modules/steal/steal.js" main="bit-docs-site/static"></script>
```

because `static.js` was importing "./packages", which was importing other packages.  It wasn't able to import those packages because "./packages" wasn't "bit-docs-site/packages".

**Comment by matthewp** [comment]
Were you using directories.lib?  Forcing System.main to have the package name will have the consequence of production bundles being written to `bundles/packageName/main` which will force users to write `main="packageName/main"` instead of just `main="main"`.  This already is required if using directories.lib. 

I'm curious why, if not using directories.lib, your default main isn't working.

**Comment by justinbmeyer** [comment]
I'm not using directories.lib

**Comment by justinbmeyer** [comment]
To get my build to work, I had to write `main: "packageName/main"`.  I think we should force people to do this.  It was confusing to my why my app didn't work with:

```
<script src="./node_modules/steal/steal.js"></script>
```

Which seems like a pretty big issue.

**Comment by matthewp** [comment]
Yeah, big issue, I agree.

I tried to recreate here: https://gist.github.com/matthewp/70e7b03088af10a5d00a79a3ec205fd6

And it works for me, so there must be something different going on.  Was the problem not that your main had a relative import?

**Comment by justinbmeyer** [comment]
in my setup `foo.js` has something like:

```js
require("some-package")
```

**Comment by matthewp** [comment]
This is the bug: https://github.com/stealjs/system-npm/issues/149

**Comment by matthewp** [comment]
I got this one @pYr0x, thanks though.
