### ISSUE TITLE
Replace steal-system with System

### ISSUE THREAD

**Issue by Bajix** [stealjs/steal#750]
Steal is currently dependent on steal-system, which is a fork of system that hasn't been updated over the past year.

The are a number of compelling reasons to make the upgrade:
- StealJS would be able to utilize all System plugins, and would no longer be responsible for maintaining in-house versions of each plugin. An excellent example of this is the [steal-sass](https://github.com/stealjs/steal-sass) plugin, which has been poorly maintained, and lacks support for even basic functionality like the @import directive, which subsequently has made StealJS unusable with SCSS.
- StealJS ES6 imports don't function properly, essentially making it impossible to work with ES6; updating System would address these limitations
- System.config defaultExtensions support
- Wildcard meta patterns
- Any paths can be overridden, allowing users to have their assets folder ( directories.lib / src ), vendor folder (or wherever else you have JSPM write dependencies ), and node_modules all in the same root directory. This sort of path overriding resolves #736, #719.
- Users could utilize JSPM to manage dependencies, which will automatically hookup the respective dependencies to remove the need for steal-builtins. Additionally, it adds placeholder index files to ensure the proper resolution of paths that would otherwise break in Steal, as it doesn't resolve CommonJS index files.
- Support for the entire [System.meta](https://github.com/systemjs/systemjs#meta-configuration) API. It's extremely important to be able to override settings on projects as a means to quickly make things work. Currently, Steal doesn't have a way to override the main file, or directories.lib, which makes it extremely challenging to consume modules from a dist folder, or to otherwise fix things like pointing towards a folder and expecting to load index.js
- Would be able to utilize JSPM to install from github, bower & npm, and take advantage of it's override capabilities

The bottom line here is that innovation never stopped happening on the SystemJS side of things, and StealJS's divergence w/ their fork of System + portability issues with CanJS have created a situation in which the DoneJS / CanJS communities are overly dependent on StealJS, but have to unnecessarily suffer from flexibility issues caused by the lack of a package manager and poor/incomplete support for [System.meta](https://github.com/systemjs/systemjs#meta-configuration).

These issues are compounded by the poor maintenance of Steal's in-house forks: [steal-less](https://github.com/stealjs/steal-less/), [steal-sass](https://github.com/stealjs/steal-sass), [steal-mocha](https://github.com/stealjs/steal-mocha), [steal-qunit](https://github.com/stealjs/steal-qunit), [steal-system](https://github.com/stealjs/steal-system/).

I strongly urge the the team here to re-consider what they're trying to accomplish with StealJS. There's an entire ecosystem of plugins for SystemJS that *should* be compatible with StealJS, and it doesn't help anyone to force users to use in-house alternatives to those plugins only to not support them adequately and leave users without any options.

**Comment by matthewp** [comment]
> Steal is currently dependent on steal-system, which is a fork of system that hasn't been updated over the past year.

Yes it has, I updated it today.

<img width="979" alt="screen shot 2016-06-09 at 4 54 16 pm" src="https://cloud.githubusercontent.com/assets/361671/15945996/d60f507e-2e62-11e6-94e1-91dbaed36eb5.png">


We used to be part of the SystemJS community and made it so that our plugins worked with SystemJS directly. This is why many of our plugins start with *system-*.  We used to contribute to SystemJS and ES6ML often as well. I'm the one that added Web Worker support to both.

However some time ago SystemJS had a dramatic change to its API that broke all of our extensions in a way that would need to be rebuilt from scratch (system-npm for example). The problem is that we have many extensions (which are different from plugins) and the SystemJS maintainer doesn't want an extension ecosystem (he's told me this directly, probably in an old issue). His recommendation was to do exactly what we did do, create our own loader that uses SystemJS under the hood.

> The bottom line here is that innovation never stopped happening on the SystemJS side of things, and StealJS's divergence w/ their fork of System + portability issues with CanJS have created a situation in which the DoneJS / CanJS communities are overly dependent on StealJS

DoneJS is CanJS and StealJS (as the core projects). That's not going to change.  CanJS should not be dependent on Steal at all. If it is, that's a bug.  CanJS has tests that verify it works in other environments like RequireJS, browserify, and globals.  I'm not aware of any other library that goes to the extent that CanJS goes to, to make sure it works everywhere.

> I strongly urge the the team here to re-consider what they're trying to accomplish with StealJS. There's an entire ecosystem of plugins for SystemJS that should be compatible with StealJS, and it doesn't help anyone to force users to use in-house alternatives to those plugins only to not support them adequately and leave users without any options.

Steal is it's own loader, that is more browser-oriented than SystemJS. Doing everything in the browser is harder that using cli tools to set up the development environment for you, or to bundle your application as you work. We are aware of the challenges and have a lot of ideas in place to compete with the popular bundlers.

**Comment by matthewp** [comment]
Some of the issues you have are coming, such as wildcard meta configuration. I hear this need often, and it will happen.  Our immediate goal is to get a stable release out, 1.0, as described here: https://github.com/stealjs/steal/issues/671. The next goal will be 1.1 which will have the new plugins API which will enable more advanced plugins: https://github.com/stealjs/steal/issues/671  You could create a plugin that loads code from JSPM if you wanted, you'd essentially have access to every underlying Steal hook.  You already *can* build a JSPM plugin if you really want, I mean we created the NPM plugin which is probably far more complex.

After 1.1 I'm not sure what will come. Upgrading to SystemJS' latest is a possibility at some point but I see no reason to do so soon (if ever). We can borrow the good ideas and incorporate them ourselves, it's not that hard. Staying up to date with a library that is not stable is much harder. Updating to latest SystemJS would probably be a month's worth of work; I can pull out meta wildcards in a half hour (or just write it myself).

**Comment by Bajix** [comment]
> However some time ago SystemJS had a dramatic change to its API that broke all of our extensions in a way that would need to be rebuilt from scratch (system-npm for example). The problem is that we have many extensions (which are different from plugins) and the SystemJS maintainer doesn't want an extension ecosystem (he's told me this directly, probably in an old issue). His recommendation was to do exactly what we did do, create our own loader that uses SystemJS under the hood.

Can you expand on what API changes were introduced that are divergent, and what the current state of divergence is there?

> DoneJS is CanJS and StealJS (as the core projects). That's not going to change. CanJS should not be dependent on Steal at all. If it is, that's a bug. CanJS has tests that verify it works in other environments like RequireJS, browserify, and globals. I'm not aware of any other library that goes to the extent that CanJS goes to, to make sure it works everywhere.

Except when it comes to stache templates which don't build anywhere other than in StealJS without extraordinary measures, or the CJS builds that randomly drop things like can/util/vdom/vdom.

> Some of the issues you have are coming, such as wildcard meta configuration. I hear this need often, and it will happen. Our immediate goal is to get a stable release out, 1.0, as described here. The next goal will be 1.1 which will have the new plugins API which will enable more advanced plugins: #671 You could create a plugin that loads code from JSPM if you wanted, you'd essentially have access to every underlying Steal hook. You already can build a JSPM plugin if you really want, I mean we created the NPM plugin which is probably far more complex.

To be clear, having StealJS load JSPM already works, and all you need to do is add the config file generated by JSPM into the package.json system.configDependencies list. What doesn't work is adding SystemJS plugins, which *almost* work, and could seemingly be made to work with a reasonable amount of effort.

You're 95% of the way there to being able to support most SystemJS plugins out of the box, and getting the last 5% would mean that Steal wouldn't need to maintain it's own ecosystem of what are essentially all forks of System's plugins anyway.

StealJS should be able to load something like (plugin-sass)[https://github.com/mobilexag/plugin-sass]. The fact that it can't only hurts the community. I know you've personally built steal-sass, and so you likely don't want to hear this, but it clearly hasn't been a high priority, and it's now been 3 months since  @Lighttree reported the issue with the `@import` directive. This is a *huge* issue, and means anyone wanting to use a SCSS-based framework such as (bourbon.io)[http://bourbon.io/], or basic things like centralized variable configuration, has no options. 

> Steal is it's own loader, that is more browser-oriented than SystemJS. Doing everything in the browser is harder that using cli tools to set up the development environment for you, or to bundle your application as you work. We are aware of the challenges and have a lot of ideas in place to compete with the popular bundlers.

That doesn't mean Steal wouldn't benefit from tools like JSPM that can address the configuration and installation shortcomings of both Steal & SystemJS. Steal and JSPM fit together quite well. The limitations w/ JSPM, are almost exclusively issues w/ Steal not handling the entire the entire config API, but as it stands right now, users could work within those limitations and get far better capabilities & flexibility than what Steal alone is able to provide.

**Comment by justinbmeyer** [comment]
Steal was rebuilt explicitly because I didn't wan't to maintain a version of `System`, but I wanted a few important features, such as modlet support. I didn't want to diverge, but this prompted the divergence: 

https://gist.github.com/justinbmeyer/c36689eab045b0a71542 

My and James Burke's advice was pretty much ignored: https://twitter.com/jrburke/status/547649399023616000

So our version of SystemJS diverged.  There's no real going back, at least not until a few ES implementations land in browsers.

> That doesn't mean Steal wouldn't benefit from tools like JSPM that can address the configuration and installation shortcomings of both Steal & SystemJS. Steal and JSPM fit together quite well. The limitations w/ JSPM, are almost exclusively issues w/ Steal not handling the entire the entire config API, but as it stands right now, users could work within those limitations and get far better capabilities & flexibility than what Steal alone is able to provide.

I'm not sure what you are saying here.  If you'd like to discuss this more, I encourage you to come to our contributors meeting tomorrow.  It sounds like you are saying that steal should use JSPM.  It can't.  StealJS is designed to make modlets work.  It's the most critical feature.  These don't work easily with JSPM.  If you don't care about modlets, use JSPM.  If they are important to you, use StealJS and help us improve our plugins / etc.  I'd also be happy to include any additional configuration settings to make SystemJS plugins more likely to work.

**Comment by Bajix** [comment]
> Steal was rebuilt explicitly because I didn't wan't to maintain a version of System, but I wanted a few important features, such as modlet support. I didn't want to diverge, but this prompted the divergence:

Ok well that's frustrating, and I think you were absolutely correct at the time, but since then they've made major improvements to the config API. That was a long time ago. Pretty sure the new config API accomplishes your use case, albeit maybe not in the way you had originally wanted, via paths.

It would be worth re-evaluating were this the big point of contention. There aren't any winners to prolonging the divergence, and it really should be a much larger concern that StealJS can't actively consume System plugins.

Steal's essentially taken on maintaining an entirely separate plugin ecosystem. That's a massive undertaking, and doesn't have a very good value proposition for either plugin authors, and by extension anyone dependent on said plugins. Authors need an avenue to build plugins for both SystemJS and StealJS.

> I'm not sure what you are saying here. If you'd like to discuss this more, I encourage you to come to our contributors meeting tomorrow. It sounds like you are saying that steal should use JSPM. It can't. StealJS is designed to make modlets work. It's the most critical feature. These don't work easily with JSPM. If you don't care about modlets, use JSPM. If they are important to you, use StealJS and help us improve our plugins / etc. I'd also be happy to include any additional configuration settings to make SystemJS plugins more likely to work.

I'm really failing to see any reason why Steal wouldn't benefit from using JSPM. Do you have a specific reason why it wouldn't work with modlets? IMO the **only** real limitations currently are that StealJS doesn't support the entire config API, which would be fairly reasonable to adopt, and the unrelated issue of plugin cross-compatibility, which maybe should be explored separately.

**Comment by justinbmeyer** [comment]
`paths` doesn't solve it, paths can't solve it.  That's the whole problem.

**Comment by matthewp** [comment]
> Can you expand on what API changes were introduced that are divergent, and what the current state of divergence is there?

Sure, 0.17 got rid of module names and replaced them with URLs, creating a normalizeSync as well; the npm plugin cannot synchronously normalize, so would have to rethink how it's architected to make that possible; also update every extension we have to also be able to synchronously normalize (we have a lot of them) and then finally update steal-tools so that it can deal with creating fake-urls for bundles since there are no longer any module names.

Hence why I said probably a month's worth of work.

> Except when it comes to stache templates which don't build anywhere other than in StealJS without extraordinary measures, or the CJS builds that randomly drop things like can/util/vdom/vdom.

There are stache plugins for Browserify and RequireJS at least. We didn't build them; the people who needed them built them. We're not obligated to create a plugin for every module loader that exists (there are many of them), there is no webpack loader that I know of, for example.  You can probably easily create a SystemJS plugin if you want.

In 3.0 there will no longer be commonjs builds; canjs will be commonjs completely and will run in Node.

> Steal wouldn't need to maintain it's own ecosystem of what are essentially all forks of System's plugins anyway.

No they aren't, I don't know where you got that idea, none of the plugins you listed above are forks.

> I know you've personally built steal-sass, and so you likely don't want to hear this, but it clearly hasn't been a high priority, and it's now been 3 months since @Lighttree reported the issue with the @import directive.

You're right it's not a high priority, I spent 30 minutes creating that plugin just for fun; just to see if it were possible. I've probably spent an hour total working on it, mostly just merging pull requests. It's not a high priority to me because I don't use it, and having talked to others that have worked on it more, sass.js is quite slow in the browser for large projects anyways.  So an @import directive issue is the least of the problems there.  Nevertheless, just because I spend 30 minutes and push something to github doesn't mean I'm obligated to maintain something indefinitely.  If anyone needs a browser-based sass plugin that badly they'll put the work in to make it.

> Does it really make sense to rebuild this entirely ecosystem internally when there are already actively maintained options that could be made to work?

Since I'm not a maintainer on that project and have no say in its direction (another huge breaking change can occur in the future) and the maintainer has told me that he doesn't want an ecosystem of extensions; then yes, building our own ecosystem is far more attractive to me.

**Comment by matthewp** [comment]
> I'm not sure what you are saying here. If you'd like to discuss this more, I encourage you to come to our contributors meeting tomorrow. 

I'd rather not, I've already talked with @Bajix about this almost every day this week and probably at least a dozen times over the last month. Frankly I'm tired of the topic. And I'd rather discuss something positive on a Friday rather than the same regurgitated arguments for why Steal should no longer exist.

**Comment by Bajix** [comment]
> I'd rather not, I've already talked with @Bajix about this almost every day this week and probably at least a dozen times over the last month. Frankly I'm tired of the topic. And I'd rather discuss something positive on a Friday rather than the same regurgitated arguments for why Steal should no longer exist.

We're on the same team here, and we all want StealJS to succeed. It's good to engage in these sorts of discussions, and the issues that I and others have encountered are quite serious, so it's not something to be dismissive of. Otherwise, how does that make you any different than Guy Bedford?

**Comment by matthewp** [comment]
We do engage, we've engaged over and over, but there has to be limits, and I've reached mine, for the time being.  If there are specific features of SystemJS that you want Steal to adopt please file issues for those features (defaultExtensions or whatever else).  "Become exactly like SystemJS" is not a valid issue, that's never going to be a project goal; if you prefer SystemJS/JSPM then you should use that.

**Comment by justinbmeyer** [comment]
I agree.  Perhaps gitter  and this issue is not the right place to discuss.  I'm not going to be able to make the donejs contributors meeting this week.  Please come to next weeks if you'd like to discuss.

**Comment by matthewp** [comment]
Just to be clear, what you are asking us to do is:

1. Become a subservient project to SystemJS; accept any changes they make whether we agree with them or not.
2. Stop our own development in order to stay current with their changes constantly.

I'm not willing to do either one of those.   So if I'm not, who's going to take on the work exactly?

**Comment by Bajix** [comment]
@matthewp I just want to be able to address the pain points that my team and I have experienced for everyone. It was very insightful to get some background on these issues, and it has made me better understand both yours and @justinbmeyer's rationale, which I'm in agreement with.

I'm not asking you to be subservient to SystemJS, but I do think that they have made changes that are applicable to StealJS, and that we would benefit from discussing those changes & incorporating the ones that make sense into the project.

I have no problem with taking ownership of different issues here, and contributing back. It's just not particularly approachable right now, and if we could settle on a specification I'll roll up my sleeves. Just need an established direction + clarity on the issues at hand.

**Comment by pYr0x** [comment]
We should distance your Self from SystemJs. We use a old version of systemjs under the hood. But there is no way to be sync with systemjs. I suggest to remove all notes about systemjs in docs. 
In future we should also rename the `Sysrem` Object. So there will be no confusion for users again.
There is no comparison with systemjs anymore!

**Comment by justinbmeyer** [comment]
Yeah, I could see renaming `system` to `steal`

**Comment by Bajix** [comment]
Maybe the biggest problem at the moment is that the documentation on System.meta is actually just (non-existent)[http://stealjs.com/docs/System.meta.html] and points to the latest SystemJS (config-api)[https://github.com/systemjs/systemjs/blob/master/docs/config-api.md]. Not only that, but the (System.paths)[http://stealjs.com/docs/System.paths.html] API differs between the two, and erroneously doesn't allow node_modules to be set down a folder in order to support having directories.lib be the baseUrl w/ node_modules still a sibling folder. Inaccurate documentation is super painful.

**Comment by pYr0x** [comment]
your are right.
please feel free to improve the documentation for other users and us.

this will help us a lot and ends confusing people that think we are a clone of SystemJS
