### ISSUE TITLE
Failed to parse SourceMap: /node_modules/steal/Promise.js.map

### ISSUE THREAD

**Issue by mjstahl** [stealjs/steal#803]
The only problem I have seen so far with steal beta3.

**Comment by matthewp** [comment]
Just when loading your app in dev?

**Comment by mjstahl** [comment]
Yeah, running `donejs develop` and then launching loading the site.

**Comment by ccummings** [comment]
The problem is actually from can-connect which includes the the Promise shim from when.js.

The offending line is [here](https://github.com/cujojs/when/blob/master/es6-shim/Promise.js#L1268) which references a .map file that is not included in the bundles steal generates.

**Comment by matthewp** [comment]
Maybe steal-tools should be stripping out sourceMappingURL comments like this.

**Comment by pYr0x** [comment]
yep i think we should remove that `sourceMapping` in production

**Comment by pYr0x** [comment]
you also get this error without using can-connect.
the problem is:
- in steal 1.0 we are not using bower_components anymore
- and your gruntfile is now using the node_module of steal-es6-module-loader https://github.com/stealjs/steal/blob/0280ccdd8f2e86d614f6c423eed3666a3af0912f/Gruntfile.js#L19
- steal-es6-module-loader is currently on version 0.17.8
- for building your steal we use the dist file `node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js` and this has a sourcemap-file in it https://github.com/stealjs/es6-module-loader/blob/abd2a1c114558ce9abcfe78b68a3270f03027076/dist/es6-module-loader.src.js#L1268

**Comment by matthewp** [comment]
@pYr0x Is this the same issue as #842?

**Comment by pYr0x** [comment]
yep

**Comment by matthewp** [comment]
Fixed by #886
