### ISSUE TITLE
Child `transpiler` option setting the System transpiler causes race-condition bugs

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#867]
Seems like if traceur is loaded, the wrong `System` can be present.  This is happening in latest `canjs/canjs` in the tests.   

https://github.com/stealjs/steal-css/issues/20 is related.

Also `System.stealURL` is undefined in _can-connect/data/worker/worker_test.js_

![canjs_tests](https://cloud.githubusercontent.com/assets/78602/19501218/46d9ed4c-9569-11e6-98f5-cc8a4cd1ca55.png)

**Comment by pYr0x** [comment]
Which version do you use? Have to tried steal 1.0?

**Comment by matthewp** [comment]
I took a quick look, and it appears the issue is that the `transpiler` changes during load.  Steal has code that prevents Traceur from overriding the global System.  But in this case the `transpiler` is being switched so that clobbering-prevention code doesn't run.

Will look more into it today, after I've gone through issues for the v1 epic.

**Comment by matthewp** [comment]
If you add this after your Steal script tag the problem goes away.

```html
<script>
(function(){
	var transpiler = System.transpiler;
	Object.defineProperty(System, "transpiler", {
		get: function() { return transpiler; },
		set: function(val){
			// Ignore this
		}
	});
})();
</script>
```

The issue is that we should ignore `transpiler` config in child packages.

**Comment by matthewp** [comment]
Still a problem when that child package is progressively loaded, reopening.
