### ISSUE TITLE
Steal 1.0 Migration Guide

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#875]
Need to write a migration guide

**Comment by matthewp** [comment]
# Items

* [ ] - Change your package.json from `system` to `steal`.

**Comment by matthewp** [comment]
Closed by https://github.com/stealjs/stealjs/pull/16

**Comment by matthewp** [comment]
Reopening for feedback.  Link is: https://stealjs.github.io/stealjs/docs/StealJS.topics.migrating-one.html

**Comment by justinbmeyer** [comment]
## 1

Instead of starting with:

> Overall most of the changes needed to upgrade from a Steal 0.16 project to Steal 1.0 are quite small.

Start with something more like: "This guide walks through upgrading from a StealJS 0.16 project to a StealJS 1.0 project.  Overall, most of the changes are quite small." .... Give people a bit more context on what the page is about. 

## 2

We should probably call StealJS ... StealJS.  Steal should be the client loader, Steal-tools the build system.  Steal is used to represent StealJS a number of places.


## 3

insert comma

> If you're not already using Steal with npm, we recommend doing so.

## 4

`Grunt Tasks` on [steal-tools](https://stealjs.github.io/stealjs/docs/steal-tools.html) should probably be moved  to into a `grunt-steal` under `ECOSYSTEM`.

It should probably link to _grunt tasks_ in "the grunt tasks for StealJS have been moved".

## 5

Grunt tasks are talked about twice in the `Grunt tasks` section.  

## 6

`Finally,` instead of `Last`

> Finally, change the configuration object to be steal rather than system like so:

## 7

Add links on steal-export and steal-live-reload in the following:

> This also applies to the steal-export and steal-live-reload tasks.

##  8

Comma after:

> Since the introduction of the npm plugin,

## 9

Change:

> Since some project names can be long this is not ideal. Aside from long names, it also means you'll need refactoring if the project is ever renamed.

to:

This wasn't ideal because project names could be long, and if your project name changed, these imports would need to be refactored.

## 10

add comma and probably remove "you can"

> In 1.0, ~ refers to your project's root.

## 11

Why `<script src="./dist/steal.production.js"></script>` ?

Does it include steal?  So bundleSteal is now true?  Also, should this include the main in the name?  

`<script src="./dist/app.production.js"></script>` 

I think we talked about this, but I can't remember what you said. 

## 12

Does `steal.import` always use the right "system"?   Or do you need to use `@loader`?

**Comment by matthewp** [comment]
Thanks, will follow up on these issues.

**Comment by mjstahl** [comment]
### Getting Steal 1.0

> npm install steal steal-tools --save-dev

does match what is in the package.json below it
```json
{
  "dependencies": {
    "steal": "^1.0.0"
  },
  "devDependencies": {
    "steal-tools": "^1.0.0"
  }
}
```
