### ISSUE TITLE
Upgrade to bit-docs

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#891]
This is a stretch goal, but worth having on the radar.

**Comment by matthewp** [comment]
Include the highlighting extension.

**Comment by justinbmeyer** [comment]
@matthewp would you want it to have the same style?  Or would you want something more like the current CanJS site?

**Comment by matthewp** [comment]
This issue is mainly about making it easier for contributors as currently a fresh clone of gh-pages doesn't build, and Windows doesn't work.  New styles would be nice down the road, but aren't blocking this issue.

**Comment by m-mujica** [comment]
- [ ] Get sidebar working 
- [ ] Fix missing ids for anchors
- [ ] Change DocJS styles to the Steal page styles

**Comment by m-mujica** [comment]
I tried using `bit-docs-html-toc` to replace the custom jquery code I added [here](https://github.com/bit-docs/bit-docs-docjs-theme/pull/1/commits/50a73ff7dc02ef23774d150fe2f175fe332da6ad), a couple of issues:

1) There is a [bug](https://github.com/bit-docs/bit-docs-html-toc/issues/2) when `.navbar` is not rendered that breaks the control (*easy fix)

2) I noticed the default outline depth=1 only lists `h2` headers, the current steal website uses depth=2, there does not seem to be a way to provide a global depth which means I'll have to edit each markdown/js file in steal/steal-tools and friends to add the depth value through the `@outline` tag. 

- @matthewp can you please confirm there is no way to set DEPTH globally? 
- If true, maybe, we could extend the `siteConfig` object to provide global DEPTH options to the 
[bit-docs-html-toc's can/control](https://github.com/bit-docs/bit-docs-html-toc/blob/764a2c920846bae00207eca4e3e6859a0a7baf5d/toc.js#L36)

3) Hacking my way from 1 and 2, I noticed that bit-docs-html-toc is collection some undesired headers

![screen shot 2016-11-04 at 09 33 00](https://cloud.githubusercontent.com/assets/724877/20005554/c8ca39f0-a271-11e6-80d9-07db6752875d.png)

(see the `{Object}` link)

This doesn't happen in the original content-list implementation because headings are queried from a specific location in the DOM https://github.com/bitovi/documentjs/blob/master/site/default/static/content_list.js#L81,

**should we assume the same DOM structure in bit-docs-html-toc? or provide an option to its can/control so it only queries for headings in specific places of the DOM?**

siteConfig
```javascript
toc: {
  depth: 2, // the global DEPTH I mentioned before
  headingsContainer: [ '.content .comment' ] // not sure about the name ¯\_(ツ)_/¯ 
}

```

@matthewp @justinbmeyer thoughts?

**Comment by m-mujica** [comment]
DEPTH=1 
![screen shot 2016-11-04 at 09 23 33](https://cloud.githubusercontent.com/assets/724877/20005833/297e87aa-a273-11e6-8805-94bede6a02b6.png)

DEPTH=2 (same as current Steal website)
![screen shot 2016-11-04 at 09 27 40](https://cloud.githubusercontent.com/assets/724877/20005844/3936c3ba-a273-11e6-883d-e15707571117.png)

**Comment by matthewp** [comment]
I don't think preserving depth 2 is important. We can just control it using `@outline` if we need depth 2 for some reason.

I think we should conform to the structure bit-docs-html-toc expects, if it's not too much work.

**Comment by m-mujica** [comment]
@matthewp ok, from https://github.com/bit-docs/bit-docs-html-toc/blob/764a2c920846bae00207eca4e3e6859a0a7baf5d/toc.js#L95 it seems bit-docs-html-toc expects the headings to inside `article` tags.... I'll take a look

**Comment by matthewp** [comment]
@m-mujica Is this done?

**Comment by m-mujica** [comment]
@matthewp I think so, I moved on to work on steal-conditional. Let me know if there is anything missing from the old website or let's just close it 💥

**Comment by matthewp** [comment]
👍
