### ISSUE TITLE
core-js es6.regexp.to-string.js incorrectly identified as AMD

### ISSUE THREAD

**Issue by bmomberger-bitovi** [stealjs/steal#937]
found in Steal 1.0 rc12

This code block is the full text of the file in question.
```
'use strict';
require('./es6.regexp.flags');
var anObject    = require('./_an-object')
  , $flags      = require('./_flags')
  , DESCRIPTORS = require('./_descriptors')
  , TO_STRING   = 'toString'
  , $toString   = /./[TO_STRING];

var define = function(fn){
  require('./_redefine')(RegExp.prototype, TO_STRING, fn, true);
};

// 21.2.5.14 RegExp.prototype.toString()
if(require('./_fails')(function(){ return $toString.call({source: 'a', flags: 'b'}) != '/a/b'; })){
  define(function toString(){
    var R = anObject(this);
    return '/'.concat(R.source, '/',
      'flags' in R ? R.flags : !DESCRIPTORS && R instanceof RegExp ? $flags.call(R) : undefined);
  });
// FF44- RegExp#toString has a wrong name
} else if($toString.name != TO_STRING){
  define(function toString(){
    return $toString.call(this);
  });
}
```

For whatever reason this file creates its own `define()` function, but the file is CJS and needs `require()` -- both `cjsRequireRegex` and `amdRegex` match the source.  Forcing this file to be CJS should be baked into Steal for this case because it's a dependency of the Babel runtime.

**Comment by matthewp** [comment]
@m-mujica while you're working on Babel stuff it would be good to look into this and see if there's anything that can be done.

**Comment by matthewp** [comment]
@bmomberger-bitovi Is this code within babel.js? Or where does it come from?

**Comment by bmomberger-bitovi** [comment]
`core-js` is its own repo, but used by Babel.  the file in question is hosted here: https://github.com/zloirock/core-js/blob/master/modules/es6.regexp.to-string.js

**Comment by matthewp** [comment]
OK, this is a problem when core-js. When is core-js used? When I test out a Babel file I don't see any core-js stuff.

**Comment by bmomberger-bitovi** [comment]
Try using generators in a class.  It should error out because you don't have a regenerator runtime.  If you then import Babel's runtime it will end up importing a lot of the core-js stuff and error out on this one.

I worked around this on a project by using Facebook's rengerator runtime instead (has no Babel deps), but some of our users may want to use the Babel one in the future.

**Comment by matthewp** [comment]
@m-mujica I remember you looked into this a little bit. Can you write up what you found here?

**Comment by m-mujica** [comment]
Yup, pretty much what Brad already mentioned.

In order to use generators, [babel-polyfill](https://babeljs.io/learn-es2015/#ecmascript-2015-features-generators) is needed. 

Babel-polyfill imports `core-js es6.regexp.to-string.js` which is a CJS module but it defines a [define](https://github.com/zloirock/core-js/blob/bbd5511c4830b81a24b406e47b25ce2ff0a501b2/modules/es6.regexp.to-string.js#L9-L11) function which messes up Steal's module detection (amd extension runs first and detects the module as AMD instead of CJS).

I created an example app with configuration to workaround the issue https://github.com/stealjs/steal-generators-example and documented it in [StealJS website](http://stealjs.com/docs/config.babelOptions.html#generators)

babel-polyfill also ships with a global file, so alternatively you could do

```javascript
import 'babel-polyfill/browser';
```

and that would work, too.

But we still have the issue of the incorrect module detection.

**Comment by matthewp** [comment]
Right, thank you. I don't think we can fix the module detection here without changing the way module detection works. Ideally we would parse the JavaScript file and detect that `define` is created within the module's scope.  This idea is being discussed in https://github.com/stealjs/steal/issues/756

Closing this issue in favor of that one.
