### ISSUE TITLE
`bower install steal` installs Steal 3.3.0

### ISSUE THREAD

**Issue by chasenlehara** [stealjs/steal#970]
This is what I get after running `bower install steal`:
```
bower cached        https://github.com/bitovi/steal.git#3.3.0
bower validate      3.3.0 against https://github.com/bitovi/steal.git#*
bower install       steal#3.3.0

steal#3.3.0 bower_components/steal
```

**Comment by matthewp** [comment]
That's the legacy Steal. I guess this wasn't a problem pre-1.0 because you'd always get something less than 1.0. Deleting the 3.x tags would likely fix it. Hopefully it's been a long enough time that we don't have to worry about legacy Steal users pointing here any more.  cc @justinbmeyer what do you think?

**Comment by justinbmeyer** [comment]
Can we give them somewhere else to point?

**Comment by matthewp** [comment]
Them who? https://github.com/bitovi/legacy-steal exists, if that's what you mean.

**Comment by matthewp** [comment]
I deleted the tags and when testing get 1.0.5 now.
