### ISSUE TITLE
steal-clone dont work with exporting a object

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal#985]
i saw this test in can-observation
```
QUnit.test('should throw if can-namespace.Observation is already defined', function() {
	stop();
	clone({
		'can-namespace': {
			Observation: {}
		}
	})
	.import('can-observation')
	.then(function() {
		ok(false, 'should throw');
		start();
	})
	.catch(function(err) {
		ok(err && err.indexOf('can-observation') >= 0, 'should throw an error about can-observation');
		start();
	});
});
```

but this test fail.

the problem is, that the cloned `can-namespace` isnt giving a plain object back.
steal-clone is given a `Module` with a method called `Observation`

testing in can-Observation does work this way
```
if (namespace.Observation) {
	throw new Error("You can't have two versions of can-observation, check your dependencies");
} else {
	module.exports = namespace.Observation = Observation;
}
```

@phillipskevin @matthewp

**Comment by phillipskevin** [comment]
This test https://github.com/canjs/can-types/blob/master/can-types_test.js#L39-L55 is working fine. Going to compare to see why the `can-observation` test is different.

**Comment by phillipskevin** [comment]
Ok, both of these are behaving the same. Doing this:

```
	clone({
		'can-namespace': {
			Observation: {}
		}
	})
```

creates a Module with an `Observation` property that only has a getter. 

The issue with the `can-observation` test is that `can-observation` loads `can-event` which tries to set another property on `can-namespace` (`namespace.batch`). This cannot be done because we're preventing extensions, here: https://github.com/stealjs/steal/blob/master/steal.js#L2385-L2386.

This test needs to correctly override the default export of `can-namespace`, like:

```
	clone({
		'can-namespace': {
			default: {
			    Observation: {}
                        },
                        __useDefault: true
		}
	})
```

This is ugly, but it is the correct way right now to override a default export with `steal-clone` so that when you import the default (like `import namespace from 'can-namespace';`) you get the passed value instead of a Module.

Maybe we should do this automatically so that if you pass an object with a single property it will turn it in to the `default`. We might also need to do this if you pass a function like:

```
	clone({
		'can-namespace': function() { ... }
	})
```

Otherwise, we need to update the documentation since right now it does not show how to override the `default` export correctly.

**Comment by pYr0x** [comment]
yep i like the idea of doing it automatically  with plain objects and functions

**Comment by matthewp** [comment]
What about an ES module that only has one export like:

```js
export function Observation(){}
```

That's not a default export, how could you mock that one if we automatically make single-export objects become the default?

**Comment by phillipskevin** [comment]
Yeah, that's the issue I see also. Make people set `__useDefault: false`? This obviously isn't a great option either.

**Comment by phillipskevin** [comment]
I think the best solution is to require users to set `default`, but set `__useDefault: true` for them so that this would work correctly: 

```
	clone({
		'can-namespace': {
			default: {
			    Observation: {}
                        }
		}
	})
```

**Comment by matthewp** [comment]
Sounds, reason, i think.
